---

- include_tasks: preflight_check.yml

# remove existing template
- block:
    - include_tasks: convert_to_vm.yml

    - include_tasks: remove_vm.yml

  when:
    - remove_template
    - template_found|bool

- include_tasks: provision.yml
  when: role_action == 'provision'