---

- block:
    - include_tasks: make_iso.yml

    - include_tasks: provision_vm.yml

    - name: add host
      add_host:
        hostname: template_vm
        ansible_host: '{{ template_vm_ip_address }}'
        host_key_checking: false
        ansible_user: "{{ local_account_username }}"
        ansible_password: "{{ local_account_password }}"
        ansible_port: "{{ vm_ansible_port | default('22') }}"
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'

    - name: run setup module
      setup:
      delegate_to: template_vm
      connection: ssh

    - block:
        - include_role:
            name: oatakan.rhn
            apply:
              delegate_to: template_vm
              connection: ssh
              become: yes

        - include_role:
            name: oatakan.rhel_upgrade
            apply:
              delegate_to: template_vm
              connection: ssh
              become: yes
          when: install_updates|bool

        - include_role:
            name: oatakan.rhel_template_build
            apply:
              delegate_to: template_vm
              connection: ssh
              become: yes

      always:
        - include_role:
            name: oatakan.rhn
            apply:
              delegate_to: template_vm
              connection: ssh
              become: yes
          vars:
            role_action: unregister

    - name: Force handlers to run before stoppping the vm
      meta: flush_handlers

    - include_tasks: stop_vm.yml

    - include_tasks: create_snapshot.yml
      when: create_snapshot|bool

    - include_tasks: convert_to_template.yml

    - include_tasks: export_ovf.yml
      when: export_ovf|bool

  rescue:
    - include_tasks: convert_to_vm.yml

    - include_tasks: remove_vm.yml
      when: remove_vm_on_error|bool

  always:
    - include_tasks: datastore_iso_remove.yml

    - name: remove temporary directory
      file:
        path: "{{ temp_directory }}"
        state: absent
      when: not export_ovf|bool
